### ISSUE TITLE
Missing Project License

### ISSUE THREAD

**Issue by sudopriestmx** [nearform/node-test-runner-workshop#44]
Hi everyone!

As I was working yesterday during the workshop and correcting the bug I mentioned on issue #43, I noticed the codebase doesn't include a license. Are there any restrictions or rules on how the code can be used, modified, and distributed? And how can one contribute, if desired? If so, would it be possible for it to be included in a license (And also perhaps on a CONTRIBUTING file at the root of the project?

Thank you for your consideration! Wish you an excellent day 😁

Jose

**Comment by simoneb** [comment]
done, we always use MIT license for our Open Source work
